### ISSUE TITLE
[BUG] Paper spigot crashes, when world was moved.

### ISSUE THREAD

**Issue by Peda1996** [trainerlord/worldsystem#116]
Paperspigot sometimes try to access data, that has already been unloaded. For this reason paper crashes. One fix Idea would be to delay the world move event.  (maybe by about one minute or so?)

```
[19:33:05] [Server thread/INFO]: [WorldSystem] Move World Data: ID35-c7cd6a27-b210-4ab0-a88b-7ae279a10704
[19:33:07] [Server thread/INFO]: [RandomTeleport] Safe location added for Farm (5/5) in 0 tries
[19:33:14] [Paper RegionFile IO Thread/FATAL]: Failed to read chunk data for task: Task for world: 'ID35-c7cd6a27-b210-4ab0-a88b-7ae279a10704' at 8,4 poi: false, hash: 1283360092
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110) ~[?:1.8.0_275]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:715) ~[?:1.8.0_275]
	at net.minecraft.server.v1_16_R3.RegionFile.a(RegionFile.java:162) ~[patched_1.16.4.jar:git-Paper-414]
	at net.minecraft.server.v1_16_R3.RegionFileCache.read(RegionFileCache.java:149) ~[patched_1.16.4.jar:git-Paper-414]
	at net.minecraft.server.v1_16_R3.IChunkLoader.read(IChunkLoader.java:104) ~[patched_1.16.4.jar:git-Paper-414]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap.read(PlayerChunkMap.java:1621) ~[patched_1.16.4.jar:git-Paper-414]
	at net.minecraft.server.v1_16_R3.WorldServer$2.readData(WorldServer.java:155) ~[patched_1.16.4.jar:git-Paper-414]
	at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) ~[patched_1.16.4.jar:git-Paper-414]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.16.4.jar:git-Paper-414]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.16.4.jar:git-Paper-414]
[19:33:14] [Paper Async Chunk Urgent Task Thread/ERROR]: Could not load chunk for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'ID35-c7cd6a27-b210-4ab0-a88b-7ae279a10704', (8,4), hashcode:496808691, priority: -1, file IO thread has dumped the relevant exception above

```

**Comment by Peda1996** [comment]
According to https://www.spigotmc.org/threads/loading-world-from-an-external-location.470857/ Also loading from other directories should be possible.

**Comment by Trinchezito** [comment]
any update on this? I keep getting this on purpur.

**Comment by CrazyCloudCraft** [comment]
> any update on this? I keep getting this on purpur.

Yea, i think that's the first think i will add to the new version.
