### ISSUE TITLE
Worldsystem not compatible with Purpur 1.20.1

### ISSUE THREAD

**Issue by Tomcatchriss** [trainerlord/WorldSystem#236]
I'm using Worldsystem on our 1.19 Buildserver and it works fine. Today I have updated to 1.20.1 and when I type /ws get, I get an error in the log:

[11:34:52 INFO]: Tomcatchriss issued server command: /ws get
[11:34:52 INFO]: [WorldSystem] /ws
[11:34:52 WARN]: [WorldSystem] Task #126 for WorldSystem v2.4.32 generated an exception
java.lang.NullPointerException: Cannot invoke "de.butzlabben.world.wrapper.CreatorAdapter.create(org.bukkit.WorldCreator, de.butzlabben.world.wrapper.SystemWorld, java.lang.Runnable)" because the return value of "de.butzlabben.world.WorldSystem.getAdapter()" is null
        at de.butzlabben.world.wrapper.SystemWorld$1.run(SystemWorld.java:161) ~[WorldSystem-2.4.32.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2006]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

- Server version (`/bukkit:version`): [11:43:01 INFO]: Current: git-Purpur-2006 (MC: 1.20.1)*
- Installed plugins (`/bukkit:plugins`):  Bukkit Plugins: (28): - AdvancedPortals, BungeeGuard, BungeeTabListPlus, BungeeTeleportManager, CoreProtect, DeluxeMentions, *EmotePlugin3, Essentials, EssentialsSpawn, FastAsyncVoxelSniper, FastAsyncWorldEdit, goBrush, goPaint, HamsterAPI, HeadDatabase, Images, LibsDisguises, LuckPerms, Multiverse-Core, PlaceholderAPI, PremiumVanish, ProtocolLib, ServerBackup, TangledMaze, Vault, VentureChat, WorldGuard, WorldSystem
- WorldGuard Report Pastebin Link (`/wg report -p`): https://paste.enginehub.org/cV48dRAEy.report

**Comment by CrazyCloudCraft** [comment]
Hello,
sorry for waiting here, but the original WorldSystem Developer has no great interest in developing the plugin.
But I created updated versions of the WorldSystem plugin to keep it up to date.
You can download the latest builds here:
https://github.com/Argantiu/WorldSystem-Updated
