### ISSUE TITLE
PLease update to 1.20.1

### ISSUE THREAD

**Issue by DjazZz0** [trainerlord/WorldSystem#237]
Hy, i want to use this plugin soooo badly, but im on 1.20.1 and when i use the /ws get command :

[14:13:19 INFO]: DjazZz_ issued server command: /ws get
[14:13:19 INFO]: [WorldSystem] [STDOUT] /ws
[14:13:19 WARN]: [WorldSystem] Task #18337 for WorldSystem v2.4.33 generated an exception
java.lang.NullPointerException: Cannot invoke "de.butzlabben.world.wrapper.CreatorAdapter.create(org.bukkit.WorldCreator, de.butzlabben.world.wrapper.SystemWorld, java.lang.Runnable)" because the return value of "de.butzlabben.WorldSystem.getAdapter()" is null
        at de.butzlabben.world.wrapper.SystemWorld$1.run(SystemWorld.java:161) ~[WorldSystem-2.4.33-1dev.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-43]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

BOOOOM an error and i saw i was not the only one with this issues using the plugin on 1.20.1

Thanks you man !!!

**Comment by CrazyCloudCraft** [comment]
Ummm... same as Issue #236
The developer is kinda inactive, you can download the newest versions here https://github.com/Argantiu/WorldSystem-Updated/releases
